"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergeHRISClient
from MergeHRISClient.model.pay_group import PayGroup
globals()['PayGroup'] = PayGroup
from MergeHRISClient.model.paginated_pay_group_list import PaginatedPayGroupList
from MergeHRISClient.api_client import ApiClient


class TestPaginatedPayGroupList(unittest.TestCase):
    """PaginatedPayGroupList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedPayGroupList(self):
        """Test PaginatedPayGroupList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedPayGroupList()  # noqa: E501

        """
        No test json responses were defined for PaginatedPayGroupList
        """
        raw_json = None

        if raw_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = raw_json

        deserialized = ApiClient().deserialize(response_mock, (PaginatedPayGroupList,), False)

        assert deserialized is not None



if __name__ == '__main__':
    unittest.main()
