"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

import MergeHRISClient
from MergeHRISClient.api.time_off_balance_api import TimeOffBalanceApi  # noqa: E501


class TestTimeOffBalanceApi(unittest.TestCase):
    """TimeOffBalanceApi unit test stubs"""

    def setUp(self):
        self.api = TimeOffBalanceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_time_off_balance_list(self):
        """Test case for time_off_balance_list

        """
        pass

    def test_time_off_balance_retrieve(self):
        """Test case for time_off_balance_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
