"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergeHRISClient
from MergeHRISClient.model.debug_model_log_summary import DebugModelLogSummary
globals()['DebugModelLogSummary'] = DebugModelLogSummary
from MergeHRISClient.model.debug_mode_log import DebugModeLog
from MergeHRISClient.api_client import ApiClient


class TestDebugModeLog(unittest.TestCase):
    """DebugModeLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDebugModeLog(self):
        """Test DebugModeLog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DebugModeLog()  # noqa: E501

        """
        No test json responses were defined for DebugModeLog
        """
        raw_json = None

        if raw_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = raw_json

        deserialized = ApiClient().deserialize(response_mock, (DebugModeLog,), False)

        assert deserialized is not None

        assert deserialized.log_id is not None
        assert deserialized.dashboard_view is not None
        assert deserialized.log_summary is not None


if __name__ == '__main__':
    unittest.main()
