"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeHRISClient
from MergeHRISClient.model.time_off import TimeOff
globals()['TimeOff'] = TimeOff
from MergeHRISClient.model.paginated_time_off_list import PaginatedTimeOffList


class TestPaginatedTimeOffList(unittest.TestCase):
    """PaginatedTimeOffList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedTimeOffList(self):
        """Test PaginatedTimeOffList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedTimeOffList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
