"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeHRISClient
from MergeHRISClient.model.create_location import CreateLocation


class TestCreateLocation(unittest.TestCase):
    """CreateLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateLocation(self):
        """Test CreateLocation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateLocation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
