# coding: utf-8

"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import MergeHRISClient
from MergeHRISClient.api.teams_api import TeamsApi  # noqa: E501
from MergeHRISClient.rest import ApiException


class TestTeamsApi(unittest.TestCase):
    """TeamsApi unit test stubs"""

    def setUp(self):
        self.api = MergeHRISClient.api.teams_api.TeamsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_teams_create(self):
        """Test case for teams_create

        """
        pass

    def test_teams_destroy(self):
        """Test case for teams_destroy

        """
        pass

    def test_teams_list(self):
        """Test case for teams_list

        """
        pass

    def test_teams_partial_update(self):
        """Test case for teams_partial_update

        """
        pass

    def test_teams_retrieve(self):
        """Test case for teams_retrieve

        """
        pass

    def test_teams_update(self):
        """Test case for teams_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
