"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

import MergeHRISClient
from MergeHRISClient.api.offices_api import OfficesApi  # noqa: E501


class TestOfficesApi(unittest.TestCase):
    """OfficesApi unit test stubs"""

    def setUp(self):
        self.api = OfficesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_offices_list(self):
        """Test case for offices_list

        """
        pass

    def test_offices_partial_update(self):
        """Test case for offices_partial_update

        """
        pass

    def test_offices_retrieve(self):
        """Test case for offices_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
