# coding: utf-8

"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import MergeHRISClient
from MergeHRISClient.api.private_token_api import PrivateTokenApi  # noqa: E501
from MergeHRISClient.rest import ApiException


class TestPrivateTokenApi(unittest.TestCase):
    """PrivateTokenApi unit test stubs"""

    def setUp(self):
        self.api = MergeHRISClient.api.private_token_api.PrivateTokenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_private_token_retrieve(self):
        """Test case for private_token_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
