# coding: utf-8

"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import MergeHRISClient
from MergeHRISClient.api.earnings_api import EarningsApi  # noqa: E501
from MergeHRISClient.rest import ApiException


class TestEarningsApi(unittest.TestCase):
    """EarningsApi unit test stubs"""

    def setUp(self):
        self.api = MergeHRISClient.api.earnings_api.EarningsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_earnings_create(self):
        """Test case for earnings_create

        """
        pass

    def test_earnings_destroy(self):
        """Test case for earnings_destroy

        """
        pass

    def test_earnings_list(self):
        """Test case for earnings_list

        """
        pass

    def test_earnings_partial_update(self):
        """Test case for earnings_partial_update

        """
        pass

    def test_earnings_retrieve(self):
        """Test case for earnings_retrieve

        """
        pass

    def test_earnings_update(self):
        """Test case for earnings_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
