"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.end_user_details_request import EndUserDetailsRequest


class TestEndUserDetailsRequest(unittest.TestCase):
    """EndUserDetailsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEndUserDetailsRequest(self):
        """Test EndUserDetailsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EndUserDetailsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
