"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

import MergeHRISClient
from MergeHRISClient.api.locations_api import LocationsApi  # noqa: E501


class TestLocationsApi(unittest.TestCase):
    """LocationsApi unit test stubs"""

    def setUp(self):
        self.api = LocationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_locations_list(self):
        """Test case for locations_list

        """
        pass

    def test_locations_retrieve(self):
        """Test case for locations_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
