# coding: utf-8

"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import MergeHRISClient
from MergeHRISClient.api.taxes_api import TaxesApi  # noqa: E501
from MergeHRISClient.rest import ApiException


class TestTaxesApi(unittest.TestCase):
    """TaxesApi unit test stubs"""

    def setUp(self):
        self.api = MergeHRISClient.api.taxes_api.TaxesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_taxes_create(self):
        """Test case for taxes_create

        """
        pass

    def test_taxes_destroy(self):
        """Test case for taxes_destroy

        """
        pass

    def test_taxes_list(self):
        """Test case for taxes_list

        """
        pass

    def test_taxes_partial_update(self):
        """Test case for taxes_partial_update

        """
        pass

    def test_taxes_retrieve(self):
        """Test case for taxes_retrieve

        """
        pass

    def test_taxes_update(self):
        """Test case for taxes_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
