"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeHRISClient
from MergeHRISClient.model.employee_payroll_run import EmployeePayrollRun
globals()['EmployeePayrollRun'] = EmployeePayrollRun
from MergeHRISClient.model.paginated_employee_payroll_run_list import PaginatedEmployeePayrollRunList


class TestPaginatedEmployeePayrollRunList(unittest.TestCase):
    """PaginatedEmployeePayrollRunList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedEmployeePayrollRunList(self):
        """Test PaginatedEmployeePayrollRunList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedEmployeePayrollRunList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
