"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeHRISClient
from MergeHRISClient.model.issue_status_enum import IssueStatusEnum
globals()['IssueStatusEnum'] = IssueStatusEnum
from MergeHRISClient.model.issue import Issue


class TestIssue(unittest.TestCase):
    """Issue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIssue(self):
        """Test Issue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Issue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
