"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergeHRISClient
from MergeHRISClient.model.account_integration import AccountIntegration
from MergeHRISClient.model.model_operation import ModelOperation
globals()['AccountIntegration'] = AccountIntegration
globals()['ModelOperation'] = ModelOperation
from MergeHRISClient.model.available_actions import AvailableActions
from MergeHRISClient.api_client import ApiClient


class TestAvailableActions(unittest.TestCase):
    """AvailableActions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAvailableActions(self):
        """Test AvailableActions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AvailableActions()  # noqa: E501

        """
        No test json responses were defined for AvailableActions
        """
        raw_json = None

        if raw_json is None:
            return

        response_mock = MagicMock()
        response_mock.data = raw_json

        deserialized = ApiClient().deserialize(response_mock, (AvailableActions,), False)

        assert deserialized is not None

        assert deserialized.integration is not None
        assert deserialized.passthrough_available is not None


if __name__ == '__main__':
    unittest.main()
