# coding: utf-8

"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import MergeHRISClient
from MergeHRISClient.api.reports_api import ReportsApi  # noqa: E501
from MergeHRISClient.rest import ApiException


class TestReportsApi(unittest.TestCase):
    """ReportsApi unit test stubs"""

    def setUp(self):
        self.api = MergeHRISClient.api.reports_api.ReportsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_reports_create(self):
        """Test case for reports_create

        """
        pass

    def test_reports_destroy(self):
        """Test case for reports_destroy

        """
        pass

    def test_reports_list(self):
        """Test case for reports_list

        """
        pass

    def test_reports_partial_update(self):
        """Test case for reports_partial_update

        """
        pass

    def test_reports_retrieve(self):
        """Test case for reports_retrieve

        """
        pass

    def test_reports_update(self):
        """Test case for reports_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
