# coding: utf-8

"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import MergeHRISClient
from MergeHRISClient.models.run_type_enum import RunTypeEnum  # noqa: E501
from MergeHRISClient.rest import ApiException

class TestRunTypeEnum(unittest.TestCase):
    """RunTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RunTypeEnum
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = MergeHRISClient.models.run_type_enum.RunTypeEnum()  # noqa: E501
        if include_optional :
            return RunTypeEnum(
            )
        else :
            return RunTypeEnum(
        )

    def testRunTypeEnum(self):
        """Test RunTypeEnum"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
