# coding: utf-8

"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import MergeHRISClient
from MergeHRISClient.models.report import Report  # noqa: E501
from MergeHRISClient.rest import ApiException

class TestReport(unittest.TestCase):
    """Report unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Report
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = MergeHRISClient.models.report.Report()  # noqa: E501
        if include_optional :
            return Report(
                name = 'Dan's Employee Review', 
                content = 'While Dan is a tremendous employee, somebody should probably be reviewing the documentation he writes, as he likes to fill them with little jokes to amuse himself.'
            )
        else :
            return Report(
        )

    def testReport(self):
        """Test Report"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
