"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeHRISClient
from MergeHRISClient.model.candidate import Candidate
globals()['Candidate'] = Candidate
from MergeHRISClient.model.paginated_candidate_list import PaginatedCandidateList


class TestPaginatedCandidateList(unittest.TestCase):
    """PaginatedCandidateList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedCandidateList(self):
        """Test PaginatedCandidateList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedCandidateList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
