"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeHRISClient
from MergeHRISClient.model.reject_reason import RejectReason
globals()['RejectReason'] = RejectReason
from MergeHRISClient.model.paginated_reject_reason_list import PaginatedRejectReasonList


class TestPaginatedRejectReasonList(unittest.TestCase):
    """PaginatedRejectReasonList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedRejectReasonList(self):
        """Test PaginatedRejectReasonList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedRejectReasonList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
