"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeHRISClient
from MergeHRISClient.model.generate_remote_key_request import GenerateRemoteKeyRequest


class TestGenerateRemoteKeyRequest(unittest.TestCase):
    """GenerateRemoteKeyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenerateRemoteKeyRequest(self):
        """Test GenerateRemoteKeyRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GenerateRemoteKeyRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
