"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

import MergeHRISClient
from MergeHRISClient.api.link_token_api import LinkTokenApi  # noqa: E501


class TestLinkTokenApi(unittest.TestCase):
    """LinkTokenApi unit test stubs"""

    def setUp(self):
        self.api = LinkTokenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_link_token_create(self):
        """Test case for link_token_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
