"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeHRISClient
from MergeHRISClient.model.race_enum import RaceEnum


class TestRaceEnum(unittest.TestCase):
    """RaceEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRaceEnum(self):
        """Test RaceEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RaceEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
