"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeHRISClient
from MergeHRISClient.model.employee_request import EmployeeRequest


class TestEmployeeRequest(unittest.TestCase):
    """EmployeeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmployeeRequest(self):
        """Test EmployeeRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EmployeeRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
