"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

import MergeHRISClient
from MergeHRISClient.api.reject_reasons_api import RejectReasonsApi  # noqa: E501


class TestRejectReasonsApi(unittest.TestCase):
    """RejectReasonsApi unit test stubs"""

    def setUp(self):
        self.api = RejectReasonsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_reject_reasons_list(self):
        """Test case for reject_reasons_list

        """
        pass

    def test_reject_reasons_partial_update(self):
        """Test case for reject_reasons_partial_update

        """
        pass

    def test_reject_reasons_retrieve(self):
        """Test case for reject_reasons_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
