"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeHRISClient
from MergeHRISClient.model.patched_scheduled_interview import PatchedScheduledInterview


class TestPatchedScheduledInterview(unittest.TestCase):
    """PatchedScheduledInterview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchedScheduledInterview(self):
        """Test PatchedScheduledInterview"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PatchedScheduledInterview()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
