"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeHRISClient
from MergeHRISClient.model.job_status_enum import JobStatusEnum


class TestJobStatusEnum(unittest.TestCase):
    """JobStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobStatusEnum(self):
        """Test JobStatusEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobStatusEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
