"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeHRISClient
from MergeHRISClient.model.attachment import Attachment
globals()['Attachment'] = Attachment
from MergeHRISClient.model.paginated_attachment_list import PaginatedAttachmentList


class TestPaginatedAttachmentList(unittest.TestCase):
    """PaginatedAttachmentList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedAttachmentList(self):
        """Test PaginatedAttachmentList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedAttachmentList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
