"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

import MergeHRISClient
from MergeHRISClient.api.available_actions_api import AvailableActionsApi  # noqa: E501


class TestAvailableActionsApi(unittest.TestCase):
    """AvailableActionsApi unit test stubs"""

    def setUp(self):
        self.api = AvailableActionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_available_actions_retrieve(self):
        """Test case for available_actions_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
