"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

import MergeHRISClient
from MergeHRISClient.api.issues_api import IssuesApi  # noqa: E501


class TestIssuesApi(unittest.TestCase):
    """IssuesApi unit test stubs"""

    def setUp(self):
        self.api = IssuesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_issues_list(self):
        """Test case for issues_list

        """
        pass

    def test_issues_retrieve(self):
        """Test case for issues_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
