# coding: utf-8

"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import MergeHRISClient
from MergeHRISClient.api.tasks_api import TasksApi  # noqa: E501
from MergeHRISClient.rest import ApiException


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self):
        self.api = MergeHRISClient.api.tasks_api.TasksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tasks_list(self):
        """Test case for tasks_list

        """
        pass

    def test_tasks_retrieve(self):
        """Test case for tasks_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
