"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeHRISClient
from MergeHRISClient.model.veteran_status_enum import VeteranStatusEnum


class TestVeteranStatusEnum(unittest.TestCase):
    """VeteranStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVeteranStatusEnum(self):
        """Test VeteranStatusEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VeteranStatusEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
