"""
    Merge HRIS API

    The unified API for building rich integrations with multiple HR Information System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeHRISClient
from MergeHRISClient.model.time_off_request import TimeOffRequest
globals()['TimeOffRequest'] = TimeOffRequest
from MergeHRISClient.model.time_off_endpoint_request import TimeOffEndpointRequest


class TestTimeOffEndpointRequest(unittest.TestCase):
    """TimeOffEndpointRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimeOffEndpointRequest(self):
        """Test TimeOffEndpointRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TimeOffEndpointRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
