"""
    Merge ATS API

    The unified API for building rich integrations with multiple Applicant Tracking System platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import MergeHRISClient
from MergeHRISClient.model.activity import Activity
globals()['Activity'] = Activity
from MergeHRISClient.model.paginated_activity_list import PaginatedActivityList


class TestPaginatedActivityList(unittest.TestCase):
    """PaginatedActivityList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedActivityList(self):
        """Test PaginatedActivityList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedActivityList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
