# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from MergeHRISClient.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from MergeHRISClient.model.access_role_enum import AccessRoleEnum
from MergeHRISClient.model.account_token import AccountToken
from MergeHRISClient.model.activity import Activity
from MergeHRISClient.model.activity_type_enum import ActivityTypeEnum
from MergeHRISClient.model.application import Application
from MergeHRISClient.model.attachment import Attachment
from MergeHRISClient.model.available_actions import AvailableActions
from MergeHRISClient.model.candidate import Candidate
from MergeHRISClient.model.department import Department
from MergeHRISClient.model.disability_status_enum import DisabilityStatusEnum
from MergeHRISClient.model.eeoc import EEOC
from MergeHRISClient.model.email_address import EmailAddress
from MergeHRISClient.model.email_address_type_enum import EmailAddressTypeEnum
from MergeHRISClient.model.end_user_details import EndUserDetails
from MergeHRISClient.model.gender_enum import GenderEnum
from MergeHRISClient.model.integration_public import IntegrationPublic
from MergeHRISClient.model.job import Job
from MergeHRISClient.model.job_interview_stage import JobInterviewStage
from MergeHRISClient.model.job_status_enum import JobStatusEnum
from MergeHRISClient.model.link_token import LinkToken
from MergeHRISClient.model.model_operation import ModelOperation
from MergeHRISClient.model.offer import Offer
from MergeHRISClient.model.offer_status_enum import OfferStatusEnum
from MergeHRISClient.model.office import Office
from MergeHRISClient.model.overall_recommendation_enum import OverallRecommendationEnum
from MergeHRISClient.model.paginated_activity_list import PaginatedActivityList
from MergeHRISClient.model.paginated_application_list import PaginatedApplicationList
from MergeHRISClient.model.paginated_attachment_list import PaginatedAttachmentList
from MergeHRISClient.model.paginated_candidate_list import PaginatedCandidateList
from MergeHRISClient.model.paginated_department_list import PaginatedDepartmentList
from MergeHRISClient.model.paginated_eeoc_list import PaginatedEEOCList
from MergeHRISClient.model.paginated_job_interview_stage_list import PaginatedJobInterviewStageList
from MergeHRISClient.model.paginated_job_list import PaginatedJobList
from MergeHRISClient.model.paginated_offer_list import PaginatedOfferList
from MergeHRISClient.model.paginated_office_list import PaginatedOfficeList
from MergeHRISClient.model.paginated_reject_reason_list import PaginatedRejectReasonList
from MergeHRISClient.model.paginated_remote_user_list import PaginatedRemoteUserList
from MergeHRISClient.model.paginated_scheduled_interview_list import PaginatedScheduledInterviewList
from MergeHRISClient.model.paginated_scorecard_list import PaginatedScorecardList
from MergeHRISClient.model.paginated_tag_list import PaginatedTagList
from MergeHRISClient.model.patched_activity import PatchedActivity
from MergeHRISClient.model.patched_application import PatchedApplication
from MergeHRISClient.model.patched_attachment import PatchedAttachment
from MergeHRISClient.model.patched_candidate import PatchedCandidate
from MergeHRISClient.model.patched_department import PatchedDepartment
from MergeHRISClient.model.patched_eeoc import PatchedEEOC
from MergeHRISClient.model.patched_email_address import PatchedEmailAddress
from MergeHRISClient.model.patched_job import PatchedJob
from MergeHRISClient.model.patched_job_interview_stage import PatchedJobInterviewStage
from MergeHRISClient.model.patched_offer import PatchedOffer
from MergeHRISClient.model.patched_office import PatchedOffice
from MergeHRISClient.model.patched_phone_number import PatchedPhoneNumber
from MergeHRISClient.model.patched_reject_reason import PatchedRejectReason
from MergeHRISClient.model.patched_remote_user import PatchedRemoteUser
from MergeHRISClient.model.patched_scheduled_interview import PatchedScheduledInterview
from MergeHRISClient.model.patched_scorecard import PatchedScorecard
from MergeHRISClient.model.patched_url import PatchedUrl
from MergeHRISClient.model.phone_number import PhoneNumber
from MergeHRISClient.model.phone_number_type_enum import PhoneNumberTypeEnum
from MergeHRISClient.model.race_enum import RaceEnum
from MergeHRISClient.model.reject_reason import RejectReason
from MergeHRISClient.model.remote_user import RemoteUser
from MergeHRISClient.model.scheduled_interview import ScheduledInterview
from MergeHRISClient.model.scheduled_interview_status_enum import ScheduledInterviewStatusEnum
from MergeHRISClient.model.scorecard import Scorecard
from MergeHRISClient.model.tag import Tag
from MergeHRISClient.model.url import Url
from MergeHRISClient.model.url_type_enum import UrlTypeEnum
from MergeHRISClient.model.veteran_status_enum import VeteranStatusEnum
from MergeHRISClient.model.visibility_enum import VisibilityEnum
