name: HRIS SDK Client

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: pip
        run: |
          pip install -r requirements.txt
      - name: test
        run: |
          pytest